CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "role" varchar NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "created_by_source" varchar,
  "updated_at" timestamp DEFAULT (now()),
  "updated_by_source" varchar
);

CREATE TABLE "photos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_id" int NOT NULL,
  "title" varchar NOT NULL,
  "price" int NOT NULL,
  "watermarked_image_url" varchar,
  "original_image_url" varchar,
  "category" varchar,
  "is_deleted" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "created_by_source" varchar,
  "updated_at" timestamp DEFAULT (now()),
  "updated_by_source" varchar
);

CREATE TABLE "carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "created_by_source" varchar,
  "updated_at" timestamp DEFAULT (now()),
  "updated_by_source" varchar
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" int NOT NULL,
  "photo_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "created_by_source" varchar,
  "updated_at" timestamp DEFAULT (now()),
  "updated_by_source" varchar
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "stripe_payment_intent_id" varchar UNIQUE,
  "status" varchar NOT NULL DEFAULT 'PENDING',
  "created_at" timestamp DEFAULT (now()),
  "created_by_source" varchar,
  "updated_at" timestamp DEFAULT (now()),
  "updated_by_source" varchar
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "photo_id" int NOT NULL,
  "price" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "created_by_source" varchar,
  "updated_at" timestamp DEFAULT (now()),
  "updated_by_source" varchar
);

CREATE TABLE "download_tokens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_item_id" int NOT NULL,
  "token" varchar UNIQUE NOT NULL,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "created_by_source" varchar,
  "updated_at" timestamp DEFAULT (now()),
  "updated_by_source" varchar
);

CREATE INDEX ON "photos" ("category");

CREATE INDEX ON "photos" ("seller_id");

CREATE INDEX ON "photos" ("title");

CREATE UNIQUE INDEX ON "cart_items" ("cart_id", "photo_id");

CREATE INDEX ON "cart_items" ("photo_id");

CREATE INDEX ON "orders" ("user_id");

CREATE INDEX ON "orders" ("status");

CREATE INDEX ON "order_items" ("order_id");

CREATE INDEX ON "order_items" ("photo_id");

CREATE INDEX ON "download_tokens" ("order_item_id");

COMMENT ON COLUMN "users"."role" IS 'GENERAL or SELLER';

COMMENT ON COLUMN "users"."created_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "users"."updated_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "photos"."price" IS '最小通貨単位(例: セント)で保存';

COMMENT ON COLUMN "photos"."created_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "photos"."updated_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "carts"."created_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "carts"."updated_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "cart_items"."created_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "cart_items"."updated_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "orders"."status" IS 'PENDING, PAID, FAILED, CANCELLED, REFUNDED';

COMMENT ON COLUMN "orders"."created_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "orders"."updated_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "order_items"."price" IS '最小通貨単位(例: セント)で保存';

COMMENT ON COLUMN "order_items"."created_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "order_items"."updated_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "download_tokens"."created_by_source" IS 'API/機能の識別子';

COMMENT ON COLUMN "download_tokens"."updated_by_source" IS 'API/機能の識別子';

ALTER TABLE "photos" ADD FOREIGN KEY ("seller_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("photo_id") REFERENCES "photos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("photo_id") REFERENCES "photos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "download_tokens" ADD FOREIGN KEY ("order_item_id") REFERENCES "order_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;
