services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: photo_ec_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/photo_ec_db

  frontend:
    build: ../frontend
    ports:
      - "5173:5173"

volumes:
  pgdata: